name: Build CV PDF

on:
  push:
    paths:
      - 'cv_pretty.tex'
      - 'assets/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-xetex lmodern

      - name: Compile LaTeX
        run: pdflatex cv_pretty.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf
          path: cv_pretty.pdf
