name: Build CV PDF

on:
  push:
    paths:
      - 'cv_pretty.tex'
      - 'assets/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-xetex lmodern

      - name: Compile LaTeX
        run: pdflatex cv_pretty.tex

      # ⬇️ New: commit the generated PDF to the repo
      - name: Commit PDF back to repo
        if: ${{ success() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdir -p build
          mv -f cv_pretty.pdf build/cv_pretty.pdf
          git add build/cv_pretty.pdf
          git commit -m "build: update generated CV [skip ci]" || echo "No changes to commit"
          git push
