name: Build CV PDF

on:
  push:
    paths:
      - 'cv_pretty.tex'
      - 'assets/**'
      - '.github/workflows/build-pdf.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile LaTeX (cached)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv_pretty.tex
          cache: true
          latexmk_use_xelatex: false         
          latexmk_shell_escape: false        
          pre_compile: |
            tlmgr update --self --all
            tlmgr install \
              collection-latexextra \
              collection-fontsrecommended \
              collection-fontsextra

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: cv-pretty
          path: cv_pretty.pdf
          if-no-files-found: error
