name: Build CV PDF

on:
  push:
    paths:
      - 'cv_pretty.tex'
      - 'assets/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install a TeX Live setup that covers all packages your template uses
      - name: Install TeX Live + latexmk
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            latexmk \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-lang-european

      # Compile (runs until success or first error)
      - name: Compile LaTeX (PDF)
        run: |
          latexmk -pdf -interaction=nonstopmode -halt-on-error -file-line-error cv_pretty.tex

      # Upload cv_pretty.pdf as a downloadable artifact
      - name: Upload PDF artifact
        if: ${{ hashFiles('cv_pretty.pdf') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: CV-PDF
          path: cv_pretty.pdf
          if-no-files-found: error
