name: Build CV PDF

on:
  push:
    paths:
      - 'cv_pretty.tex'
      - 'assets/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv_pretty.tex
          latexmk_use_xelatex: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv_pretty
          path: cv_pretty.pdf
